baseURL = 'https://unstoppa61e.github.io/'
languageCode = 'ja-JP'
title = 'unstoppa61e blog'
publishDir = "docs"
theme = 'hyde'
canonifyurls = true
[params]
  paginate = 10
  themeColor = "theme-base-0b"
