baseURL = 'https://unstoppa61e.github.io/'
languageCode = 'ja-JP'
title = 'Stop Me If You Can'
publishDir = "docs"
theme = 'hyde'
canonifyurls = true
[params]
  paginate = 10
  themeColor = "theme-base-0b"
